name: duka_letu
description: An e-commerce app built with Flutter and Firebase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.13.5
  cloud_functions: ^4.6.6   # 🔥 Added for FirebaseFunctions
  js: ^0.7.1                # 🔥 Added for PromiseJsImpl support

  # Other Dependencies
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.5
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
