// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXWHIrf2eRGHiGF_rR1u283hnC5Fp48w',
    appId: '1:105587401:web:09e5128495bd0cfc7d2318',
    messagingSenderId: '105587401',
    projectId: 'duka-letu-01-61a86',
    authDomain: 'duka-letu-01-61a86.firebaseapp.com',
    storageBucket: 'duka-letu-01-61a86.firebasestorage.app',
    measurementId: 'G-EZN2VMTNME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX2K5jDNAUysAPxdVM35KiaMNzudeDp_g',
    appId: '1:105587401:android:a31dec1902d232787d2318',
    messagingSenderId: '105587401',
    projectId: 'duka-letu-01-61a86',
    storageBucket: 'duka-letu-01-61a86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBphdxmTKkIauE8wMAuCn6RoymViD5KVXQ',
    appId: '1:105587401:ios:b6e8923c63fe5e077d2318',
    messagingSenderId: '105587401',
    projectId: 'duka-letu-01-61a86',
    storageBucket: 'duka-letu-01-61a86.firebasestorage.app',
    iosBundleId: 'com.example.dukaLetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBphdxmTKkIauE8wMAuCn6RoymViD5KVXQ',
    appId: '1:105587401:ios:b6e8923c63fe5e077d2318',
    messagingSenderId: '105587401',
    projectId: 'duka-letu-01-61a86',
    storageBucket: 'duka-letu-01-61a86.firebasestorage.app',
    iosBundleId: 'com.example.dukaLetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpXWHIrf2eRGHiGF_rR1u283hnC5Fp48w',
    appId: '1:105587401:web:f65b5197c36a381f7d2318',
    messagingSenderId: '105587401',
    projectId: 'duka-letu-01-61a86',
    authDomain: 'duka-letu-01-61a86.firebaseapp.com',
    storageBucket: 'duka-letu-01-61a86.firebasestorage.app',
    measurementId: 'G-XVT8VVF1S9',
  );
}
